language: python
sudo: false
cache: pip
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
matrix:
  include:
    - python: '3.6'
    - python: '3.7'
      dist: xenial
      sudo: required
      after_success:
        - pip3 install -r docs/requirements.txt
        - sphinx-build -b html docs docs/build
        - sphinx-build -b linkcheck docs docs/build
        - codecov
before_install:
  - python --version
  - pip3 --version
  - uname -a
  - lsb_release -a
install:
  - pip3 install . -r tests/requirements.txt pytest-travis-fold
  - pip3 freeze
script:
  - pytest -vvra --cov=marshmallow_union
notifications:
  email:
    on_success: never
    on_failure: always
